### ISSUE TITLE
Overview over when different key people are online

### ISSUE THREAD

**Issue by 16patsle** [phaser-discord/administration#4]
I'm thinking it would be a good idea to create an overview over when key people on the server usually are online. Key people meaning moderators/admins and possibly also helpers. We don't have that many yet. But it would be good to prepare in advance.

I'm mostly active/available for answering between 7 and 20 GMT (7am and 8pm). My timezone is CET/CEST

**Comment by jdotrjs** [comment]
I think general geographic region might be better than hours? ... or at least I couldn't figure out how to characterize mine since i'll randomly drop in to check on chat even if i shouldn't be there 😛

So I'd be like: San Francisco, CA area / spotty coverage almost all day

**Comment by 16patsle** [comment]
It would be more like which hours you could be expected to drop in, not necessarily online all the time. Just area/timezone would probably work just fine too. That way, people would get a rough idea of when to expect people being online.

**Comment by Fabadiculous** [comment]
I am in Brisbane Australia and will probably be on ~7am - 8pm (maybe 9pm). (AEST) Which means 9pm to 10AM on the next day GMT.

I am at uni during the days though so I won't always be immediately available.

**Comment by 16patsle** [comment]
What would be the most logical way to present this type of info? Write the timezone in #readme on discord?

Maybe a separate file on github to track more detailed time zone info?

**Comment by jdotrjs** [comment]
Something like this?

![availabilityish](https://user-images.githubusercontent.com/37101247/37777911-e2418332-2da5-11e8-8436-eac3275e3a12.png)

**Comment by jdotrjs** [comment]
As to where it'd go... I'm not sure. the #readme message is getting busy and I'm concerned dropping a graphic in there would be too much (though maybe it's worth trying?)

With respect to generation: github also has a built in CSV viewer so we could try to do something similar to that graphic with that which would have the benefit of being super easy to update. Other options could include somebody making a google account that and sharing a calendar with this information mapped into it. I think that would benefit by always being in the viewer's local time zone instead of making people convert from UTC to it.

Wherever it ends up we should make sure to caveat that these are the hours you're _most likely_ to find people around vs promising staffing since we all have lives.

**Comment by 16patsle** [comment]
A calendar sounds like a good idea, the question is if it's a reasonable solution given the time it takes to set up.

We could alternatively just put it some place on github with the image, and link to it in #readme.

The CSV stuff sounds like it's worth to explore at least.

**Comment by jdotrjs** [comment]
Haha, fair enough -- I'm not going to do it but wouldn't stop somebody else :P

the CSV would look like https://github.com/phaser-discord/administration/blob/jdotrjs/csv/staff-availability.csv

**Comment by AleBles** [comment]
Added my most online hours to the sheet, outside of those availability is flaky

**Comment by 16patsle** [comment]
I merged #21 now. We're going for CSV at the moment, then.

**Comment by jdotrjs** [comment]
Closing this since it seems we've got something in place; surfacing it is a different question and probably part of #3
